In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score

# Load dataset
df = pd.read_csv(r"C:\Users\SANSKRUTI\OneDrive\Desktop\THIRD YEAR (TE)\DSBDA CODES\data6.csv")

# Display first rows
print(df.head())

# Features and target variable
X = df.drop('Species', axis=1)
y = df['Species']

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=0
)

# Create Naive Bayes model
model = GaussianNB()

# Train model
model.fit(X_train, y_train)

# Predict values
y_pred = model.predict(X_test)

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix")
print(cm)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)

print("\nAccuracy :", accuracy)

# Error Rate
error_rate = 1 - accuracy

print("Error Rate :", error_rate)

# For binary calculation example
TP = cm[0][0]
FP = cm[0][1]
FN = cm[1][0]
TN = cm[1][1]

print("\nTrue Positive :", TP)
print("False Positive :", FP)
print("False Negative :", FN)
print("True Negative :", TN)

# Precision
precision = TP / (TP + FP)

print("\nPrecision :", precision)

# Recall
recall = TP / (TP + FN)

print("Recall :", recall)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
Confusion Matrix
[[13  0  0]
 [ 0 16  0]
 [ 0  0  9]]

Accuracy : 1.0
Error Rate : 0.0

True Positive : 13
False Positive : 0
False Negative : 0
True Negative : 16

Precision : 1.0
Recall : 1.0
